#!/bin/sh
__EXPLORER_BACKEND_MAINNET_HTTP_HOST__=${BACKEND_MAINNET_HTTP_HOST:=127.0.0.1}
__EXPLORER_BACKEND_MAINNET_HTTP_PORT__=${BACKEND_MAINNET_HTTP_PORT:=8999}
__EXPLORER_FRONTEND_HTTP_PORT__=${FRONTEND_HTTP_PORT:=8080}

__PROXIED_SERVICES__=${PROXIED_SERVICES:=false}
__PROXIED_SERVICES_HOST__=${PROXIED_SERVICES_HOST:=https://bchexplorer.cash}

if [ "${__PROXIED_SERVICES__}" = "true" ]; then
  sed -i "s|proxy_pass https://bchexplorer.cash;|proxy_pass ${__PROXIED_SERVICES_HOST__};|g" /etc/nginx/conf.d/nginx-explorer.conf
fi

sed -i "s/__EXPLORER_BACKEND_MAINNET_HTTP_HOST__/${__EXPLORER_BACKEND_MAINNET_HTTP_HOST__}/g" /etc/nginx/conf.d/nginx-explorer.conf
sed -i "s/__EXPLORER_BACKEND_MAINNET_HTTP_PORT__/${__EXPLORER_BACKEND_MAINNET_HTTP_PORT__}/g" /etc/nginx/conf.d/nginx-explorer.conf

cp /etc/nginx/nginx.conf /patch/nginx.conf
sed -i "s/__EXPLORER_FRONTEND_HTTP_PORT__/${__EXPLORER_FRONTEND_HTTP_PORT__}/g" /patch/nginx.conf
cat /patch/nginx.conf > /etc/nginx/nginx.conf

# Runtime overrides - read env vars defined in docker compose

__MAINNET_ENABLED__=${MAINNET_ENABLED:=true}
__TESTNET4_ENABLED__=${TESTNET4_ENABLED:=false}
__SCALENET_ENABLED__=${SCALENET_ENABLED:=false}
__CHIPNET_ENABLED__=${CHIPNET_ENABLED:=false}
__ITEMS_PER_PAGE__=${ITEMS_PER_PAGE:=10}
__KEEP_BLOCKS_AMOUNT__=${KEEP_BLOCKS_AMOUNT:=8}
__NGINX_PROTOCOL__=${NGINX_PROTOCOL:=http}
__NGINX_HOSTNAME__=${NGINX_HOSTNAME:=localhost}
__NGINX_PORT__=${NGINX_PORT:=8999}
__MIN_BLOCK_SIZE_UNITS__=${MIN_BLOCK_SIZE_UNITS:=32000000}
__MEMPOOL_BLOCKS_AMOUNT__=${MEMPOOL_BLOCKS_AMOUNT:=1}
__BASE_MODULE__=${BASE_MODULE:=explorer}
__ROOT_NETWORK__=${ROOT_NETWORK:=}
__WEBSITE_URL__=${WEBSITE_URL:=https://bchexplorer.cash}
__MINING_DASHBOARD__=${MINING_DASHBOARD:=true}
__AUDIT__=${AUDIT:=false}
__MAINNET_BLOCK_AUDIT_START_HEIGHT__=${MAINNET_BLOCK_AUDIT_START_HEIGHT:=0}
__TESTNET4_BLOCK_AUDIT_START_HEIGHT__=${TESTNET4_BLOCK_AUDIT_START_HEIGHT:=0}
__SCALENET_BLOCK_AUDIT_START_HEIGHT__=${SCALENET_BLOCK_AUDIT_START_HEIGHT:=0}
__CHIPNET_BLOCK_AUDIT_START_HEIGHT__=${CHIPNET_BLOCK_AUDIT_START_HEIGHT:=0}
__MAINNET_TX_FIRST_SEEN_START_HEIGHT__=${MAINNET_TX_FIRST_SEEN_START_HEIGHT:=0}
__TESTNET4_TX_FIRST_SEEN_START_HEIGHT__=${TESTNET4_TX_FIRST_SEEN_START_HEIGHT:=0}
__SCALENET_TX_FIRST_SEEN_START_HEIGHT__=${SCALENET_TX_FIRST_SEEN_START_HEIGHT:=0}
__CHIPNET_TX_FIRST_SEEN_START_HEIGHT__=${CHIPNET_TX_FIRST_SEEN_START_HEIGHT:=0}
__SERVICES_API__=${SERVICES_API:=https://bchexplorer.cash/api/v1/services}
__HISTORICAL_PRICE__=${HISTORICAL_PRICE:=true}
__ADDITIONAL_CURRENCIES__=${ADDITIONAL_CURRENCIES:=false}
__STRATUM_ENABLED__=${STRATUM_ENABLED:=false}
__NOTIFICATION_MESSAGE__=${NOTIFICATION_MESSAGE:=}

# Export as environment variables to be used by envsubst
export __MAINNET_ENABLED__
export __TESTNET4_ENABLED__
export __SCALENET_ENABLED__
export __CHIPNET_ENABLED__
export __ITEMS_PER_PAGE__
export __KEEP_BLOCKS_AMOUNT__
export __NGINX_PROTOCOL__
export __NGINX_HOSTNAME__
export __NGINX_PORT__
export __MIN_BLOCK_SIZE_UNITS__
export __MEMPOOL_BLOCKS_AMOUNT__
export __BASE_MODULE__
export __ROOT_NETWORK__
export __WEBSITE_URL__
export __MINING_DASHBOARD__
export __AUDIT__
export __MAINNET_BLOCK_AUDIT_START_HEIGHT__
export __TESTNET4_BLOCK_AUDIT_START_HEIGHT__
export __SCALENET_BLOCK_AUDIT_START_HEIGHT__
export __CHIPNET_BLOCK_AUDIT_START_HEIGHT__
export __MAINNET_TX_FIRST_SEEN_START_HEIGHT__
export __TESTNET4_TX_FIRST_SEEN_START_HEIGHT__
export __SCALENET_TX_FIRST_SEEN_START_HEIGHT__
export __CHIPNET_TX_FIRST_SEEN_START_HEIGHT__
export __SERVICES_API__
export __HISTORICAL_PRICE__
export __ADDITIONAL_CURRENCIES__
export __STRATUM_ENABLED__
export __NOTIFICATION_MESSAGE__

folder=$(find /var/www/explorer -name "config.js" | xargs dirname)
echo ${folder}
envsubst < ${folder}/config.template.js > ${folder}/config.js

exec "$@"
