# redirect /api to /docs/api
location = /api {
	return 308 https://$host/docs/api;
}
location = /api/ {
	return 308 https://$host/docs/api;
}

# redirect /testnet4/api to /testnet4/docs/api
location = /testnet4/api {
	return 308 https://$host/testnet4/docs/api;
}
location = /testnet4/api/ {
	return 308 https://$host/testnet4/docs/api;
}

# redirect /scalenet/api to /scalenet/docs/api
location = /scalenet/api {
	return 308 https://$host/scalenet/docs/api;
}
location = /scalenet/api/ {
	return 308 https://$host/scalenet/docs/api;
}

# redirect /chipnet/api to /chipnet/docs/api
location = /chipnet/api {
	return 308 https://$host/chipnet/docs/api;
}
location = /chipnet/api/ {
	return 308 https://$host/chipnet/docs/api;
}

