user __NGINX_USER__;
pid /var/run/nginx.pid;

worker_processes auto;
worker_rlimit_nofile 100000;

events {
	worker_connections 9000;
	multi_accept on;
}

http {
	# DNS servers for on-demand resolution, change if desired
	resolver 8.8.8.8;

	# include default mime types
	include __NGINX_ETC_FOLDER__/mime.types;
	default_type application/octet-stream;

	# HTTP basic configuration
	include explorer/production/nginx/http-basic.conf;
	include explorer/production/nginx/http-acl.conf;
	include explorer/production/nginx/http-proxy-cache.conf;
	include explorer/production/nginx/http-language.conf;

	# match preview/unfurl bot user-agents
	map $http_user_agent $unfurlprefix {
		default "";
	}

	# BCH Explorer configuration
	include explorer/production/nginx/upstream-explorer.conf;


	# BCH Explorer
	server {
		# clearnet v4/v6
		#listen 443 ssl http2;
		#listen [::]:443 ssl http2;
		server_name _;

		# set cors headers if necessary
		set $cors_approved_origin '';

		# tor v3
		listen 127.0.0.1:81;
		set $onion "__NGINX_EXPLORER_ONION__";

		# for services from bchexplorer.cash like contributors on about page
		set $bchExplorerServices "https://bchexplorer.cash";
		set $bchExplorerUnfurler "http://127.0.0.1:8001";
		set $bchExplorerSSR "http://127.0.0.1:4201";

		# for BCH Explorer backend daemons, see upstream-explorer.conf
		set $bchExplorerMainnet "http://bch-explorer-mainnet";
		set $bchExplorerTestnet "http://bch-explorer-testnet";
		set $bchExplorerTestnet4 "http://bch-explorer-testnet4";
		set $bchExplorerScalenet "http://bch-explorer-scalenet";
		set $bchExplorerChipnet "http://bch-explorer-chipnet";

		# filesystem paths
		root /explorer/public_html/mainnet/;
		access_log /var/log/nginx/explorer-access.log;
		error_log /var/log/nginx/explorer-error.log;

		# site configuration
		include explorer/production/nginx/server-explorer.conf;
	}
}
