include explorer/production/nginx/server-common.conf;
include explorer/production/nginx/location-redirects.conf;
include explorer/production/nginx/location-api-v1-services.conf;
include explorer/production/nginx/location-api.conf;
include explorer/production/nginx/location-testnet4-api.conf;
include explorer/production/nginx/location-scalenet-api.conf;
include explorer/production/nginx/location-chipnet-api.conf;
