#!/usr/bin/env zsh
check_mempoolspace_frontend_git_hash() {
	echo -n $(curl -s --connect-to "::node${1}.${2}.mempool.space:443" https://mempool.space/en-US/resources/config.js|grep GIT_COMMIT_HASH_MEMPOOL_SPACE|cut -d "'" -f2|cut -c1-8)
}
check_mempoolfoss_frontend_git_hash() {
	echo -n $(curl -s "https://node${1}.${2}.mempool.space/resources/config.js"|grep GIT_COMMIT_HASH|cut -d "'" -f2|cut -c1-8)
}
check_mempoolfoss_backend_git_hash() {
	echo -n $(curl -s "https://node${1}.${2}.mempool.space/api/v1/backend-info"|jq -r .gitCommit 2>/dev/null|cut -c1-8)
}
check_mempoolspace_frontend_md5_hash() {
	echo -n $(curl -s --connect-to "::node${1}.${2}.mempool.space:443" https://mempool.space|md5|cut -c1-8)
}
check_mempoolfoss_frontend_md5_hash() {
	echo -n $(curl -s https://node${1}.${2}.mempool.space|md5|cut -c1-8)
}
check_contributors_md5_hash() {
	echo -n $(curl -s --connect-to "::node${1}.${2}.mempool.space:443" https://mempool.space/api/v1/contributors|md5|cut -c1-8)
}
for site in hnl sv1 fra tk7 va1 sg1;do
	echo "${site}"
	for node in 201 202 203 204 205 206 207 208 209 210 211 212 213 214;do
		[ "${site}" = "sv1" ] && [ "${node}" -lt 202 ] && continue
		[ "${site}" = "sv1" ] && [ "${node}" -gt 203 ] && continue
		[ "${site}" = "sg1" ] && [ "${node}" -gt 204 ] && continue
		[ "${site}" = "hnl" ] && [ "${node}" -gt 204 ] && continue
		[ "${site}" = "tk7" ] && [ "${node}" -gt 206 ] && continue
		echo -n "node${node}.${site}: "
#		check_mempoolspace_frontend_git_hash $node $site
#		echo -n " "
#		check_mempoolfoss_frontend_git_hash $node $site
#		echo -n " "
#		check_mempoolfoss_backend_git_hash $node $site
#		echo -n " "
#		check_mempoolspace_frontend_md5_hash $node $site
#		echo -n " "
#		check_mempoolfoss_frontend_md5_hash $node $site
#		echo -n " "
#		check_contributors_md5_hash $node $site
	done
done
