#!/bin/sh

# EXPLORER
__EXPLORER_NETWORK__=${EXPLORER_NETWORK:=mainnet}
__EXPLORER_BACKEND__=${EXPLORER_BACKEND:=electrum}
__EXPLORER_ENABLED__=${EXPLORER_ENABLED:=true}
__EXPLORER_OFFICIAL__=${EXPLORER_OFFICIAL:=false}
__EXPLORER_HTTP_PORT__=${BACKEND_HTTP_PORT:=8999}
__EXPLORER_SPAWN_CLUSTER_PROCS__=${EXPLORER_SPAWN_CLUSTER_PROCS:=0}
__EXPLORER_UNIX_SOCKET_PATH__=${EXPLORER_UNIX_SOCKET_PATH:=""}
__EXPLORER_API_URL_PREFIX__=${EXPLORER_API_URL_PREFIX:=/api/v1/}
__EXPLORER_POLL_RATE_MS__=${EXPLORER_POLL_RATE_MS:=2000}
__EXPLORER_CACHE_DIR__=${EXPLORER_CACHE_DIR:=./cache}
__EXPLORER_CACHE_ENABLED__=${EXPLORER_CACHE_ENABLED:=true}
__EXPLORER_CLEAR_PROTECTION_MINUTES__=${EXPLORER_CLEAR_PROTECTION_MINUTES:=20}
__EXPLORER_RECOMMENDED_FEE_PERCENTILE__=${EXPLORER_RECOMMENDED_FEE_PERCENTILE:=50}
__EXPLORER_MIN_BLOCK_SIZE_UNITS__=${EXPLORER_MIN_BLOCK_SIZE_UNITS:=32000000}
__EXPLORER_INITIAL_BLOCKS_AMOUNT__=${EXPLORER_INITIAL_BLOCKS_AMOUNT:=8}
__EXPLORER_MEMPOOL_BLOCKS_AMOUNT__=${EXPLORER_MEMPOOL_BLOCKS_AMOUNT:=1}
__EXPLORER_INDEXING_BLOCKS_AMOUNT__=${EXPLORER_INDEXING_BLOCKS_AMOUNT:=11000}
__EXPLORER_BLOCKS_SUMMARIES_INDEXING__=${EXPLORER_BLOCKS_SUMMARIES_INDEXING:=false}
__EXPLORER_GOGGLES_INDEXING__=${EXPLORER_GOGGLES_INDEXING:=false}
__EXPLORER_USE_SECOND_NODE_FOR_MINFEE__=${EXPLORER_USE_SECOND_NODE_FOR_MINFEE:=false}
__EXPLORER_EXTERNAL_ASSETS__=${EXPLORER_EXTERNAL_ASSETS:=[]}
__EXPLORER_EXTERNAL_MAX_RETRY__=${EXPLORER_EXTERNAL_MAX_RETRY:=1}
__EXPLORER_EXTERNAL_RETRY_INTERVAL__=${EXPLORER_EXTERNAL_RETRY_INTERVAL:=0}
__EXPLORER_USER_AGENT__=${EXPLORER_USER_AGENT:=explorer}
__EXPLORER_STDOUT_LOG_MIN_PRIORITY__=${EXPLORER_STDOUT_LOG_MIN_PRIORITY:=info}
__EXPLORER_AUTOMATIC_POOLS_UPDATE__=${EXPLORER_AUTOMATIC_POOLS_UPDATE:=true}
__EXPLORER_POOLS_JSON_URL__=${EXPLORER_POOLS_JSON_URL:=https://gitlab.melroy.org/bitcoincash/mining-pools/-/raw/main/pools-v2.json}
__EXPLORER_POOLS_JSON_TREE_URL__=${EXPLORER_POOLS_JSON_TREE_URL:=https://gitlab.melroy.org/api/v4/projects/199/repository/tree}
__EXPLORER_POOLS_UPDATE_DELAY__=${EXPLORER_POOLS_UPDATE_DELAY:=604800}
__EXPLORER_POOLS_SOURCE__=${EXPLORER_POOLS_SOURCE:=gitlab}
__EXPLORER_AUDIT__=${EXPLORER_AUDIT:=false}
__EXPLORER_RUST_GBT__=${EXPLORER_RUST_GBT:=true}
__EXPLORER_LIMIT_GBT__=${EXPLORER_LIMIT_GBT:=false}
__EXPLORER_MAX_BLOCKS_BULK_QUERY__=${EXPLORER_MAX_BLOCKS_BULK_QUERY:=0}
__EXPLORER_DISK_CACHE_BLOCK_INTERVAL__=${EXPLORER_DISK_CACHE_BLOCK_INTERVAL:=6}
__EXPLORER_PRICE_UPDATES_PER_HOUR__=${EXPLORER_PRICE_UPDATES_PER_HOUR:=1}
__EXPLORER_MAX_TRACKED_ADDRESSES__=${EXPLORER_MAX_TRACKED_ADDRESSES:=1}

# CORE_RPC
__CORE_RPC_HOST__=${CORE_RPC_HOST:=127.0.0.1}
__CORE_RPC_PORT__=${CORE_RPC_PORT:=8332}
__CORE_RPC_USERNAME__=${CORE_RPC_USERNAME:=explorer}
__CORE_RPC_PASSWORD__=${CORE_RPC_PASSWORD:=explorer}
__CORE_RPC_TIMEOUT__=${CORE_RPC_TIMEOUT:=60000}
__CORE_RPC_COOKIE__=${CORE_RPC_COOKIE:=false}
__CORE_RPC_COOKIE_PATH__=${CORE_RPC_COOKIE_PATH:=""}
__CORE_RPC_DEBUG_LOG_PATH__=${CORE_RPC_DEBUG_LOG_PATH:=""}

# ELECTRUM
__ELECTRUM_HOST__=${ELECTRUM_HOST:=127.0.0.1}
__ELECTRUM_PORT__=${ELECTRUM_PORT:=50001}
__ELECTRUM_TLS_ENABLED__=${ELECTRUM_TLS_ENABLED:=false}


# SECOND_CORE_RPC
__SECOND_CORE_RPC_HOST__=${SECOND_CORE_RPC_HOST:=127.0.0.1}
__SECOND_CORE_RPC_PORT__=${SECOND_CORE_RPC_PORT:=8332}
__SECOND_CORE_RPC_USERNAME__=${SECOND_CORE_RPC_USERNAME:=explorer}
__SECOND_CORE_RPC_PASSWORD__=${SECOND_CORE_RPC_PASSWORD:=explorer}
__SECOND_CORE_RPC_TIMEOUT__=${SECOND_CORE_RPC_TIMEOUT:=60000}
__SECOND_CORE_RPC_COOKIE__=${SECOND_CORE_RPC_COOKIE:=false}
__SECOND_CORE_RPC_COOKIE_PATH__=${SECOND_CORE_RPC_COOKIE_PATH:=""}

# DATABASE
__DATABASE_ENABLED__=${DATABASE_ENABLED:=true}
__DATABASE_HOST__=${DATABASE_HOST:=127.0.0.1}
__DATABASE_SOCKET__=${DATABASE_SOCKET:=""}
__DATABASE_PORT__=${DATABASE_PORT:=3306}
__DATABASE_DATABASE__=${DATABASE_DATABASE:=explorer}
__DATABASE_USERNAME__=${DATABASE_USERNAME:=explorer}
__DATABASE_PASSWORD__=${DATABASE_PASSWORD:=explorer}
__DATABASE_TIMEOUT__=${DATABASE_TIMEOUT:=180000}
__DATABASE_PID_DIR__=${DATABASE_PID_DIR:=""}
__DATABASE_POOL_SIZE__=${DATABASE_POOL_SIZE:=100}

# SYSLOG
__SYSLOG_ENABLED__=${SYSLOG_ENABLED:=false}
__SYSLOG_HOST__=${SYSLOG_HOST:=127.0.0.1}
__SYSLOG_PORT__=${SYSLOG_PORT:=514}
__SYSLOG_MIN_PRIORITY__=${SYSLOG_MIN_PRIORITY:=info}
__SYSLOG_FACILITY__=${SYSLOG_FACILITY:=local7}

# STATISTICS
__STATISTICS_ENABLED__=${STATISTICS_ENABLED:=true}
__STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD__=${STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD:=150}

# SOCKS5PROXY
__SOCKS5PROXY_ENABLED__=${SOCKS5PROXY_ENABLED:=false}
__SOCKS5PROXY_USE_ONION__=${SOCKS5PROXY_USE_ONION:=true}
__SOCKS5PROXY_HOST__=${SOCKS5PROXY_HOST:=localhost}
__SOCKS5PROXY_PORT__=${SOCKS5PROXY_PORT:=9050}
__SOCKS5PROXY_USERNAME__=${SOCKS5PROXY_USERNAME:=""}
__SOCKS5PROXY_PASSWORD__=${SOCKS5PROXY_PASSWORD:=""}

# EXTERNAL_DATA_SERVER
__EXTERNAL_DATA_SERVER_EXPLORER_API__=${EXTERNAL_DATA_SERVER_EXPLORER_API:=https://bchexplorer.cash/api/v1}
__EXTERNAL_DATA_SERVER_EXPLORER_ONION__=${EXTERNAL_DATA_SERVER_EXPLORER_ONION:=http://someuniondomain.onion/api/v1}

# REPLICATION
__REPLICATION_ENABLED__=${REPLICATION_ENABLED:=false}
__REPLICATION_AUDIT__=${REPLICATION_AUDIT:=false}
__REPLICATION_AUDIT_START_HEIGHT__=${REPLICATION_AUDIT_START_HEIGHT:=774000}
__REPLICATION_STATISTICS__=${REPLICATION_STATISTICS:=false}
__REPLICATION_STATISTICS_START_TIME__=${REPLICATION_STATISTICS_START_TIME:=1481932800}
__REPLICATION_SERVERS__=${REPLICATION_SERVERS:=[]}

# MELROY_EXPLORER_SERVICES
__MELROY_EXPLORER_SERVICES_API__=${MELROY_EXPLORER_SERVICES_API:="https://bchexplorer.cash/api/v1/services"}

# STRATUM
__STRATUM_ENABLED__=${STRATUM_ENABLED:=false}
__STRATUM_API__=${STRATUM_API:="http://localhost:1234"}

# VALKEY
__VALKEY_ENABLED__=${VALKEY_ENABLED:=false}
__VALKEY_UNIX_SOCKET_PATH__=${VALKEY_UNIX_SOCKET_PATH:=""}
__VALKEY_BATCH_QUERY_BASE_SIZE__=${VALKEY_BATCH_QUERY_BASE_SIZE:=5000}

# FIAT_PRICE
__FIAT_PRICE_ENABLED__=${FIAT_PRICE_ENABLED:=true}
__FIAT_PRICE_PAID__=${FIAT_PRICE_PAID:=false}
__FIAT_PRICE_API_KEY__=${FIAT_PRICE_API_KEY:=""}

mkdir -p "${__EXPLORER_CACHE_DIR__}"

sed -i "s!__EXPLORER_NETWORK__!${__EXPLORER_NETWORK__}!g" explorer-config.json
sed -i "s!__EXPLORER_BACKEND__!${__EXPLORER_BACKEND__}!g" explorer-config.json
sed -i "s!__EXPLORER_ENABLED__!${__EXPLORER_ENABLED__}!g" explorer-config.json
sed -i "s!__EXPLORER_OFFICIAL__!${__EXPLORER_OFFICIAL__}!g" explorer-config.json
sed -i "s!__EXPLORER_HTTP_PORT__!${__EXPLORER_HTTP_PORT__}!g" explorer-config.json
sed -i "s!__EXPLORER_SPAWN_CLUSTER_PROCS__!${__EXPLORER_SPAWN_CLUSTER_PROCS__}!g" explorer-config.json
sed -i "s!__EXPLORER_UNIX_SOCKET_PATH__!${__EXPLORER_UNIX_SOCKET_PATH__}!g" explorer-config.json
sed -i "s!__EXPLORER_API_URL_PREFIX__!${__EXPLORER_API_URL_PREFIX__}!g" explorer-config.json
sed -i "s!__EXPLORER_POLL_RATE_MS__!${__EXPLORER_POLL_RATE_MS__}!g" explorer-config.json
sed -i "s!__EXPLORER_CACHE_DIR__!${__EXPLORER_CACHE_DIR__}!g" explorer-config.json
sed -i "s!__EXPLORER_CACHE_ENABLED__!${__EXPLORER_CACHE_ENABLED__}!g" explorer-config.json
sed -i "s!__EXPLORER_CLEAR_PROTECTION_MINUTES__!${__EXPLORER_CLEAR_PROTECTION_MINUTES__}!g" explorer-config.json
sed -i "s!__EXPLORER_RECOMMENDED_FEE_PERCENTILE__!${__EXPLORER_RECOMMENDED_FEE_PERCENTILE__}!g" explorer-config.json
sed -i "s!__EXPLORER_MIN_BLOCK_SIZE_UNITS__!${__EXPLORER_MIN_BLOCK_SIZE_UNITS__}!g" explorer-config.json
sed -i "s!__EXPLORER_INITIAL_BLOCKS_AMOUNT__!${__EXPLORER_INITIAL_BLOCKS_AMOUNT__}!g" explorer-config.json
sed -i "s!__EXPLORER_MEMPOOL_BLOCKS_AMOUNT__!${__EXPLORER_MEMPOOL_BLOCKS_AMOUNT__}!g" explorer-config.json
sed -i "s!__EXPLORER_INDEXING_BLOCKS_AMOUNT__!${__EXPLORER_INDEXING_BLOCKS_AMOUNT__}!g" explorer-config.json
sed -i "s!__EXPLORER_BLOCKS_SUMMARIES_INDEXING__!${__EXPLORER_BLOCKS_SUMMARIES_INDEXING__}!g" explorer-config.json
sed -i "s!__EXPLORER_GOGGLES_INDEXING__!${__EXPLORER_GOGGLES_INDEXING__}!g" explorer-config.json
sed -i "s!__EXPLORER_USE_SECOND_NODE_FOR_MINFEE__!${__EXPLORER_USE_SECOND_NODE_FOR_MINFEE__}!g" explorer-config.json
sed -i "s!__EXPLORER_EXTERNAL_ASSETS__!${__EXPLORER_EXTERNAL_ASSETS__}!g" explorer-config.json
sed -i "s!__EXPLORER_EXTERNAL_MAX_RETRY__!${__EXPLORER_EXTERNAL_MAX_RETRY__}!g" explorer-config.json
sed -i "s!__EXPLORER_EXTERNAL_RETRY_INTERVAL__!${__EXPLORER_EXTERNAL_RETRY_INTERVAL__}!g" explorer-config.json
sed -i "s!__EXPLORER_USER_AGENT__!${__EXPLORER_USER_AGENT__}!g" explorer-config.json
sed -i "s!__EXPLORER_STDOUT_LOG_MIN_PRIORITY__!${__EXPLORER_STDOUT_LOG_MIN_PRIORITY__}!g" explorer-config.json
sed -i "s!__EXPLORER_AUTOMATIC_POOLS_UPDATE__!${__EXPLORER_AUTOMATIC_POOLS_UPDATE__}!g" explorer-config.json
sed -i "s!__EXPLORER_POOLS_JSON_URL__!${__EXPLORER_POOLS_JSON_URL__}!g" explorer-config.json
sed -i "s!__EXPLORER_POOLS_JSON_TREE_URL__!${__EXPLORER_POOLS_JSON_TREE_URL__}!g" explorer-config.json
sed -i "s!__EXPLORER_POOLS_UPDATE_DELAY__!${__EXPLORER_POOLS_UPDATE_DELAY__}!g" explorer-config.json
sed -i "s!__EXPLORER_POOLS_SOURCE__!${__EXPLORER_POOLS_SOURCE__}!g" explorer-config.json
sed -i "s!__EXPLORER_AUDIT__!${__EXPLORER_AUDIT__}!g" explorer-config.json
sed -i "s!__EXPLORER_RUST_GBT__!${__EXPLORER_RUST_GBT__}!g" explorer-config.json
sed -i "s!__EXPLORER_LIMIT_GBT__!${__EXPLORER_LIMIT_GBT__}!g" explorer-config.json
sed -i "s!__EXPLORER_CPFP_INDEXING__!${__EXPLORER_CPFP_INDEXING__}!g" explorer-config.json
sed -i "s!__EXPLORER_MAX_BLOCKS_BULK_QUERY__!${__EXPLORER_MAX_BLOCKS_BULK_QUERY__}!g" explorer-config.json
sed -i "s!__EXPLORER_DISK_CACHE_BLOCK_INTERVAL__!${__EXPLORER_DISK_CACHE_BLOCK_INTERVAL__}!g" explorer-config.json
sed -i "s!__EXPLORER_PRICE_UPDATES_PER_HOUR__!${__EXPLORER_PRICE_UPDATES_PER_HOUR__}!g" explorer-config.json
sed -i "s!__EXPLORER_MAX_TRACKED_ADDRESSES__!${__EXPLORER_MAX_TRACKED_ADDRESSES__}!g" explorer-config.json

sed -i "s!__CORE_RPC_HOST__!${__CORE_RPC_HOST__}!g" explorer-config.json
sed -i "s!__CORE_RPC_PORT__!${__CORE_RPC_PORT__}!g" explorer-config.json
sed -i "s!__CORE_RPC_USERNAME__!${__CORE_RPC_USERNAME__}!g" explorer-config.json
sed -i "s!__CORE_RPC_PASSWORD__!${__CORE_RPC_PASSWORD__}!g" explorer-config.json
sed -i "s!__CORE_RPC_TIMEOUT__!${__CORE_RPC_TIMEOUT__}!g" explorer-config.json
sed -i "s!__CORE_RPC_COOKIE__!${__CORE_RPC_COOKIE__}!g" explorer-config.json
sed -i "s!__CORE_RPC_COOKIE_PATH__!${__CORE_RPC_COOKIE_PATH__}!g" explorer-config.json
sed -i "s!__CORE_RPC_DEBUG_LOG_PATH__!${__CORE_RPC_DEBUG_LOG_PATH__}!g" explorer-config.json

sed -i "s!__ELECTRUM_HOST__!${__ELECTRUM_HOST__}!g" explorer-config.json
sed -i "s!__ELECTRUM_PORT__!${__ELECTRUM_PORT__}!g" explorer-config.json
sed -i "s!__ELECTRUM_TLS_ENABLED__!${__ELECTRUM_TLS_ENABLED__}!g" explorer-config.json

sed -i "s!__SECOND_CORE_RPC_HOST__!${__SECOND_CORE_RPC_HOST__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_PORT__!${__SECOND_CORE_RPC_PORT__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_USERNAME__!${__SECOND_CORE_RPC_USERNAME__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_PASSWORD__!${__SECOND_CORE_RPC_PASSWORD__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_TIMEOUT__!${__SECOND_CORE_RPC_TIMEOUT__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_COOKIE__!${__SECOND_CORE_RPC_COOKIE__}!g" explorer-config.json
sed -i "s!__SECOND_CORE_RPC_COOKIE_PATH__!${__SECOND_CORE_RPC_COOKIE_PATH__}!g" explorer-config.json

sed -i "s!__DATABASE_ENABLED__!${__DATABASE_ENABLED__}!g" explorer-config.json
sed -i "s!__DATABASE_HOST__!${__DATABASE_HOST__}!g" explorer-config.json
sed -i "s!__DATABASE_SOCKET__!${__DATABASE_SOCKET__}!g" explorer-config.json
sed -i "s!__DATABASE_PORT__!${__DATABASE_PORT__}!g" explorer-config.json
sed -i "s!__DATABASE_DATABASE__!${__DATABASE_DATABASE__}!g" explorer-config.json
sed -i "s!__DATABASE_USERNAME__!${__DATABASE_USERNAME__}!g" explorer-config.json
sed -i "s!__DATABASE_PASSWORD__!${__DATABASE_PASSWORD__}!g" explorer-config.json
sed -i "s!__DATABASE_TIMEOUT__!${__DATABASE_TIMEOUT__}!g" explorer-config.json
sed -i "s!__DATABASE_PID_DIR__!${__DATABASE_PID_DIR__}!g" explorer-config.json
sed -i "s!__DATABASE_POOL_SIZE__!${__DATABASE_POOL_SIZE__}!g" explorer-config.json

sed -i "s!__SYSLOG_ENABLED__!${__SYSLOG_ENABLED__}!g" explorer-config.json
sed -i "s!__SYSLOG_HOST__!${__SYSLOG_HOST__}!g" explorer-config.json
sed -i "s!__SYSLOG_PORT__!${__SYSLOG_PORT__}!g" explorer-config.json
sed -i "s!__SYSLOG_MIN_PRIORITY__!${__SYSLOG_MIN_PRIORITY__}!g" explorer-config.json
sed -i "s!__SYSLOG_FACILITY__!${__SYSLOG_FACILITY__}!g" explorer-config.json

sed -i "s!__STATISTICS_ENABLED__!${__STATISTICS_ENABLED__}!g" explorer-config.json
sed -i "s!__STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD__!${__STATISTICS_TX_PER_SECOND_SAMPLE_PERIOD__}!g" explorer-config.json

sed -i "s!__SOCKS5PROXY_ENABLED__!${__SOCKS5PROXY_ENABLED__}!g" explorer-config.json
sed -i "s!__SOCKS5PROXY_USE_ONION__!${__SOCKS5PROXY_USE_ONION__}!g" explorer-config.json
sed -i "s!__SOCKS5PROXY_HOST__!${__SOCKS5PROXY_HOST__}!g" explorer-config.json
sed -i "s!__SOCKS5PROXY_PORT__!${__SOCKS5PROXY_PORT__}!g" explorer-config.json
sed -i "s!__SOCKS5PROXY_USERNAME__!${__SOCKS5PROXY_USERNAME__}!g" explorer-config.json
sed -i "s!__SOCKS5PROXY_PASSWORD__!${__SOCKS5PROXY_PASSWORD__}!g" explorer-config.json

sed -i "s!__EXTERNAL_DATA_SERVER_EXPLORER_API__!${__EXTERNAL_DATA_SERVER_EXPLORER_API__}!g" explorer-config.json
sed -i "s!__EXTERNAL_DATA_SERVER_EXPLORER_ONION__!${__EXTERNAL_DATA_SERVER_EXPLORER_ONION__}!g" explorer-config.json

# REPLICATION
sed -i "s!__REPLICATION_ENABLED__!${__REPLICATION_ENABLED__}!g" explorer-config.json
sed -i "s!__REPLICATION_AUDIT__!${__REPLICATION_AUDIT__}!g" explorer-config.json
sed -i "s!__REPLICATION_AUDIT_START_HEIGHT__!${__REPLICATION_AUDIT_START_HEIGHT__}!g" explorer-config.json
sed -i "s!__REPLICATION_STATISTICS__!${__REPLICATION_STATISTICS__}!g" explorer-config.json
sed -i "s!__REPLICATION_STATISTICS_START_TIME__!${__REPLICATION_STATISTICS_START_TIME__}!g" explorer-config.json
sed -i "s!__REPLICATION_SERVERS__!${__REPLICATION_SERVERS__}!g" explorer-config.json

# MELROY_EXPLORER_SERVICES
sed -i "s!__MELROY_EXPLORER_SERVICES_API__!${__MELROY_EXPLORER_SERVICES_API__}!g" explorer-config.json

# STRATUM
sed -i "s!__STRATUM_ENABLED__!${__STRATUM_ENABLED__}!g" explorer-config.json
sed -i "s!__STRATUM_API__!${__STRATUM_API__}!g" explorer-config.json

# VALKEY
sed -i "s!__VALKEY_ENABLED__!${__VALKEY_ENABLED__}!g" explorer-config.json
sed -i "s!__VALKEY_UNIX_SOCKET_PATH__!${__VALKEY_UNIX_SOCKET_PATH__}!g" explorer-config.json
sed -i "s!__VALKEY_BATCH_QUERY_BASE_SIZE__!${__VALKEY_BATCH_QUERY_BASE_SIZE__}!g" explorer-config.json

# FIAT_PRICE
sed -i "s!__FIAT_PRICE_ENABLED__!${__FIAT_PRICE_ENABLED__}!g" explorer-config.json
sed -i "s!__FIAT_PRICE_PAID__!${__FIAT_PRICE_PAID__}!g" explorer-config.json
sed -i "s!__FIAT_PRICE_API_KEY__!${__FIAT_PRICE_API_KEY__}!g" explorer-config.json

node /backend/package/index.js
