import { AddressTxSummary, Block, ChainStats } from './backend-api.interface';

export interface OptimizedMempoolStats {
  added: number;
  count: number;
  bytes_per_second: number;
  total_fee: number;
  mempool_byte_size: number;
  sizes: number[];
}

export interface DifficultyAdjustment {
  scheduleOffsetSeconds: number;
  difficultyDriftPercent: number;
  currentBits: string;
  nextBits: string;
  timeAvg: number;
}

export interface AddressInformation {
  isvalid: boolean; //  (boolean) If the address is valid or not. If not, this is the only property returned.
  isvalid_parent?: boolean; //  (boolean) Elements only
  address: string; //  (string) The bitcoin address validated
  scriptPubKey: string; //  (string) The hex-encoded scriptPubKey generated by the address
  isscript: boolean; //  (boolean) If the key is a script
}

export interface AuditStatus {
  bitcoinBlocks: number;
  bitcoinHeaders: number;
  lastBlockAudit: number;
  isAuditSynced: boolean;
}

export interface ITranslators {
  [language: string]: string;
}

/**
 * PoolRanking component
 */
export interface SinglePoolStats {
  poolId: number;
  poolUniqueId: number; // unique global pool id
  name: string;
  link: string;
  blockCount: number;
  emptyBlocks: number;
  rank: number;
  share: number;
  lastEstimatedHashrate: number;
  lastEstimatedHashrate3d: number;
  lastEstimatedHashrate1w: number;
  emptyBlockRatio: string;
  logo: string;
  slug: string;
  avgMatchRate: number;
  avgFeeDelta: number;
}
export interface PoolsStats {
  blockCount: number;
  lastEstimatedHashrate: number;
  lastEstimatedHashrate3d: number;
  lastEstimatedHashrate1w: number;
  pools: SinglePoolStats[];
}

/**
 * Pool component
 */
export interface PoolInfo {
  id: number | null; // mysql row id
  name: string;
  link: string;
  regexes: string; // JSON array
  addresses: string; // JSON array
  emptyBlocks: number;
  slug: string;
  poolUniqueId: number;
  unique_id: number;
}
export interface PoolStat {
  pool: PoolInfo;
  blockCount: {
    all: number;
    '24h': number;
    '1w': number;
  };
  blockShare: {
    all: number;
    '24h': number;
    '1w': number;
  };
  estimatedHashrate: number;
  avgBlockHealth: number;
  totalReward: number;
}

export interface BlockExtension {
  totalFees?: number;
  medianFee?: number;
  minFee?: number;
  maxFee?: number;
  feeRange?: number[];
  feePercentiles?: number[] | null;
  reward?: number;
  coinbaseRaw?: string;
  coinbaseAddress?: string;
  coinbaseAddresses?: string[];
  coinbaseSignature?: string;
  coinbaseSignatureAscii?: string;
  header?: string;
  avgFee?: number;
  avgFeeRate?: number;
  avgTxSize?: number;
  totalInputs?: number;
  totalOutputs?: number;
  totalInputAmt?: number | null;
  totalOutputAmt?: number;
  utxoSetChange?: number;
  utxoSetSize?: number | null;
  matchRate?: number;
  expectedFees?: number;
  expectedSize?: number;
  expectedWeight?: number;
  feeDelta?: number;
  sizeDelta?: number;
  similarity?: number;
  size?: number;
  pool?: {
    id: number;
    name: string;
    slug: string;
    minerNames: string[] | null;
  };
  orphans?: {
    height: number;
    hash: string;
    status:
      | 'invalid'
      | 'active'
      | 'valid-fork'
      | 'valid-headers'
      | 'headers-only';
    prevhash: string;
  }[];
}

export interface BlockExtended extends Block {
  extras?: BlockExtension;
}

export interface BlockAudit extends BlockExtended {
  version: number;
  unseenTxs?: string[];
  missingTxs: string[];
  addedTxs: string[];
  freshTxs: string[];
  sigopTxs: string[];
  matchRate: number;
  expectedFees: number;
  expectedSize: number;
  feeDelta?: number;
  sizeDelta?: number;
  txDelta?: number;
  template: TransactionStripped[];
  transactions: TransactionStripped[];
}

export interface TransactionStripped {
  txid: string;
  fee: number;
  size: number;
  value: number;
  rate?: number; // effective fee rate
  flags?: number | null;
  time?: number;
  status?:
    | 'found'
    | 'missing'
    | 'sigop'
    | 'fresh'
    | 'added'
    | 'censored'
    | 'selected'
    | 'matched'
    | 'unmatched';
  context?: 'projected' | 'actual' | 'stale' | 'canonical';
}

export interface MempoolPosition {
  block: number;
  size: number;
  feeDelta?: number;
}

export interface RewardStats {
  startBlock: number;
  endBlock: number;
  totalReward: number;
  totalFee: number;
  totalTx: number;
}

export interface BlockSizes {
  sizes: {
    timestamp: number;
    avgHeight: number;
    avgSize: number;
  }[];
}

export interface BlockTimeDiffs {
  timeDiffs: {
    timestamp: number;
    avgHeight: number;
    avgTimeDiff: number;
  }[];
}

export interface BlockTxCounts {
  transactions: {
    timestamp: number;
    avgHeight: number;
    avgTxCount: number;
  }[];
}

export interface UtxoSize {
  utxos: {
    timestamp: number;
    avgHeight: number;
    avgUtxoSize: number;
  }[];
}

export interface AuditScore {
  hash: string;
  matchRate?: number;
}

export interface TestMempoolAcceptResult {
  txid: string;
  wtxid: string;
  allowed?: boolean;
  size?: number;
  fees?: {
    base: number;
    'effective-feerate': number;
    'effective-includes': string[];
  };
  ['reject-reason']?: string;
}

export interface SubmitPackageResult {
  package_msg: string;
  'tx-results': { [wtxid: string]: TxResult };
  'replaced-transactions'?: string[];
}

export interface TxResult {
  txid: string;
  'other-wtxid'?: string;
  size?: number;
  fees?: {
    base: number;
    'effective-feerate'?: number;
    'effective-includes'?: string[];
  };
  error?: string;
}
export interface WalletAddress {
  address: string;
  active: boolean;
  stats: ChainStats;
  transactions: AddressTxSummary[];
}

export interface Treasury {
  id: number;
  name: string;
  wallet: string;
  enterprise: string;
  verifiedAddresses: string[];
  balances?: { balance: number; time: number }[];
}

export interface ChainTip {
  height: number;
  hash: string;
  branchlen: number;
  status:
    | 'invalid'
    | 'active'
    | 'valid-fork'
    | 'valid-headers'
    | 'headers-only';
}

export interface StaleTip extends ChainTip {
  stale: BlockExtended;
  canonical: BlockExtended;
}
