services:
  bch-explorer-web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "bch-explorer-api"
    image: registry.melroy.org/bitcoincash/bitcoin-cash-explorer/bch-explorer-frontend:3.11.12
    user: 1000:1000
    container_name: bch-explorer-web
    restart: always
    stop_grace_period: 1m
    networks:
      - bch_explorer_external_network
    command: "./wait-for bch-explorer-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 80:8080

  bch-explorer-api:
    environment:
      EXPLORER_BACKEND: "electrum"
      EXPLORER_NETWORK: "mainnet"
      EXPLORER_INDEXING_BLOCKS_AMOUNT: "-1"
      CORE_RPC_HOST: "172.27.0.1"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "explorer"
      CORE_RPC_PASSWORD: "explorer"
      ELECTRUM_HOST: "172.27.0.1"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "bch-explorer-db"
      DATABASE_DATABASE: "explorer"
      DATABASE_USERNAME: "explorer"
      DATABASE_PASSWORD: "admin"
      STATISTICS_ENABLED: "true"
    image: registry.melroy.org/bitcoincash/bitcoin-cash-explorer/bch-explorer-backend:3.11.12
    user: 1000:1000
    container_name: bch-explorer-api
    restart: always
    stop_grace_period: 1m
    networks:
      - bch_explorer_external_network
    command: "./wait-for-it.sh bch-explorer-db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
    ulimits:
      nofile:
        soft: 165535
        hard: 500000

  bch-explorer-db:
    environment:
      MYSQL_DATABASE: "explorer"
      MYSQL_USER: "explorer"
      MYSQL_PASSWORD: "explorer"
      MYSQL_ROOT_PASSWORD: "admin"
      MARIADB_AUTO_UPGRADE: "1"
    image: mariadb:12.2.1
    user: 1000:1000
    container_name: bch-explorer-db
    restart: always
    stop_grace_period: 1m
    networks:
      - bch_explorer_external_network
    volumes:
      - ./mysql/data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 165535
        hard: 500000

networks:
  bch_explorer_external_network:
